[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/api/:splat"
[[redirects]]
    from = "/*"
    status = 200
    to = "/index.html"
